server:
  port: 80

# 项目相关配置
app:
  # 名称
  name: dami_news
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2022
  # 文件路径
  uploadPath: E:/img

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://sh-cynosdbmysql-grp-psmzc27s.sql.tencentcdb.com:23916/springboot_demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: E5h3qpSH
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

mybatis:
  typeAliasesPackage: com.tencent.**.domain
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql